server:
  port: 8080

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
    url: jdbc:postgresql://localhost:5432/girasol
    username: postgres
    password: ENC(t0ADr6e0/4nZxomqfQCWRK2oIKgUIWO3)
  jpa:
    properties:
      hibernate:
        default_schema: girasol
        ddl_auto: update
        show_sql: true